"""init migration

Revision ID: 801db9f04e73
Revises: 
Create Date: 2023-01-19 19:55:29.596699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801db9f04e73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.VARCHAR(length=25), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('laki-laki', 'perempuan'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
